---
title: "absenteeism_charts"
author: "Nina Schoonover"
date: "2025-05-13"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

###############################################################
# ACPS Student Success Audit - Absenteeism Charts       
# Authors: Nina Schoonover     
# Last revised: 2025-05-13
# Summary: A document that creates charts on Absenteeism
#          for ACPS Audit


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(janitor)
library(ggplot2)

# Load Data

total_absenteeism <- read_csv("../data/total_absenteeism.csv")


```


## Chronic Absenteeism Plots

```{r pressure, echo=FALSE}
## Absenteeism Chart by Membership Group

ggplot() +
      geom_line(data = total_absenteeism %>% dplyr::filter(subgroup!="Asian",
                                                             subgroup!="Black",
                                                             subgroup!="Hispanic",
                                                             subgroup!="Multiracial",
                                                             subgroup!="White"),
                aes(x = school_year, y= percent, group = subgroup, color = subgroup)) +
      theme_minimal() +
      scale_y_continuous(limits=c(0,50), breaks=seq(0,100,10),minor_breaks=seq(0,100,5)) +
      scale_x_discrete(labels=c("2015-16", "2016-17","2017-18","2018-19","2019-20","2020-21","2021-22",
                              "2022-23","2023-24")) +
      labs(x="School Year", y="Percent Enrolled" ) +
      scale_color_manual(name = "subgroup",
                        values = c("#f8be3d", "#04994b", "#0c9ed9", "#9d02d7"))  + 
      theme(legend.title=element_blank(), 
      legend.position = "top", 
      legend.text = element_text(size = 12, hjust=.5), 
      axis.text.x = element_text(color = "black", size = 12, angle = 45, hjust = 1), 
      axis.ticks = element_blank(), 
      plot.title.position= "plot", 
      plot.caption.position = "plot", 
      axis.text.y = element_text(size = 12), 
      text = element_text(size = 12, family="sans"), 
      plot.title = element_text(size = 16, hjust=.65), 
      plot.caption = element_text(size = 14)) 

 ggsave("../plots/absentee_group.png",device="png",width=8,height=4,units="in")

## Absenteeism Chart by Race
ggplot() +
      geom_line(data = total_absenteeism %>% dplyr::filter(subgroup!="All Students",
                                                             subgroup!="SPED",
                                                             subgroup!="Economically Disadvantaged",
                                                             subgroup!="English Learners"),
                aes(x = school_year, y= percent, group = subgroup, color = subgroup)) +
      theme_minimal() +
      scale_y_continuous(limits=c(0,50), breaks=seq(0,100,10),minor_breaks=seq(0,100,5)) +
      scale_x_discrete(labels=c("2015-16", "2016-17","2017-18","2018-19","2019-20","2020-21","2021-22",
                              "2022-23","2023-24")) +
      labs(x="School Year", y="Percent Enrolled") +
      scale_color_manual(name = "subgroup",
                        values = c("#04994b", "#fa8775", "#9d02d7", "#0c9ed9", "#f8be3d"))  + 
      theme(legend.title=element_blank(), 
      legend.position = "top", 
      legend.text = element_text(size = 12, hjust=.5), 
      axis.text.x = element_text(color = "black", size = 12, angle = 45, hjust = 1), 
      axis.ticks = element_blank(), 
      plot.title.position= "plot", 
      plot.caption.position = "plot", 
      axis.text.y = element_text(size = 12), 
      text = element_text(size = 12, family="sans"), 
      plot.title = element_text(size = 16, hjust=.65), 
      plot.caption = element_text(size = 14)) 

 ggsave("../plots/absentee_race.png",device="png",width=8,height=4,units="in")




```


