---
title: "Advanced Coursework Charts"
author: "Asha Muralidharan"
date: "2025-05-07"
output: html_document
---

##############################################################
# ACPS Student Success Audit - Advanced Coursework Charts       
# Authors: Asha Muralidharan     
# GitHub: asha-ec                              
# Last revised: 2025-05-06
# Summary: A document that creates charts on Graduation Rates
#          for ACPS Audit
##############################################################

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

##############################################################
# Call Libraries
##############################################################

library(readxl)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(extrafont)

advanced_div <- read_csv("../data/ACPS_advanced_coursework_div_data_2019-23.csv")
advanced_school <- read_csv("../data/ACPS_advanced_coursework_school_data_2019-23.csv")

```

```{r ap_by_school}
ggplot() +
  geom_line(data=advanced_school %>% dplyr::filter(data_level=="All"),
            aes(x=year,y=perc_ap, group=school_name,color=school_name))+
  theme_minimal()+
  scale_y_continuous(limits=c(0,100),breaks=seq(0,100,10),minor_breaks=seq(0,100,5))+
  labs(x="School Year", y="Percentage of Students", 
       title="Percentage of ACPS Students Enrolled in at least\nOne AP Course by School:   2019-20 to 2023-24")+
  geom_text(size = 5, hjust=0.5, vjust=-1, color="black") + 
  scale_color_manual(values = c("#9d02d7","#0c9ed9","#f8be3d")) + 
  theme(legend.title=element_blank(), 
        legend.position = "top", 
        legend.text = element_text(size = 12, hjust=.5), 
        axis.text.x = element_text(color = "black", size = 12, angle = 45, hjust = 1), 
        axis.ticks = element_blank(), 
        plot.title.position= "plot", 
        plot.caption.position = "plot", 
        axis.text.y = element_text(size = 12), 
        text = element_text(size = 12, family="sans"), 
        plot.title = element_text(size = 16, hjust=.65), 
        plot.caption = element_text(size = 14)) 
  

```

```{r de_by_school}
ggplot() +
  geom_line(data=advanced_school %>% dplyr::filter(data_level=="All"),
            aes(x=year,y=perc_de, group=school_name,color=school_name))+
  theme_minimal()+
  scale_y_continuous(limits=c(0,100),breaks=seq(0,100,10),minor_breaks=seq(0,100,5))+
  labs(x="School Year", y="Percentage of Students", 
       title="Percentage of ACPS Students Enrolled in at least \nOne DE Course by School: 2019-20 to 2023-24")+
  geom_text(size = 5, hjust=0.5, vjust=-1, color="black") +
  scale_color_manual(values = c("#9d02d7","#0c9ed9","#f8be3d")) +
  theme(legend.title=element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 12, hjust=.5),
        axis.text.x = element_text(color = "black", size = 12, angle = 45, hjust = 1),
        axis.ticks = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot",
        axis.text.y = element_text(size = 12),
        text = element_text(size = 12, family="sans"),
        plot.title = element_text(size = 16, hjust=.65),
        plot.caption = element_text(size = 14))

```

```{r ap_by_race}
ggplot() +
  geom_line(data=advanced_div %>% dplyr::filter(data_level=="Race",
                                                   student_group!="American Indian or Alaska Native",
                                                   student_group!="Native Hawaiian or Pacific Islander",
                                                   student_group!="Native Hawaiian  or Pacific Islander"),
            aes(x=year,y=perc_ap, group=student_group,color=student_group))+
  theme_minimal()+
  scale_y_continuous(limits=c(0,100),breaks=seq(0,100,10),minor_breaks=seq(0,100,5))+
  labs(x="School Year", y="Percentage of Students", 
       title="Percentage of ACPS Students Enrolled in at least \nOne AP Course by Race: 2019-20 to 2023-24")+
  geom_text(size = 5, hjust=0.5, vjust=-1, color="black") +
  scale_color_manual(values = c("#04994b","#fa8775","#9d02d7","#0c9ed9", "#f8be3d")) +
  theme(legend.title=element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 12, hjust=.5),
        axis.text.x = element_text(color = "black", size = 12, angle = 45, hjust = 1),
        axis.ticks = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot",
        axis.text.y = element_text(size = 12),
        text = element_text(size = 12, family="sans"),
        plot.title = element_text(size = 16, hjust=.65),
        plot.caption = element_text(size = 14))

```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r de_by_race}
ggplot() +
  geom_line(data=advanced_div %>% dplyr::filter(data_level=="Race",
                                                   student_group!="American Indian or Alaska Native",
                                                   student_group!="Native Hawaiian or Pacific Islander",
                                                   student_group!="Native Hawaiian  or Pacific Islander"),
            aes(x=year,y=perc_de, group=student_group,color=student_group))+
  theme_minimal()+
  scale_y_continuous(limits=c(0,100),breaks=seq(0,100,10),minor_breaks=seq(0,100,5))+
  labs(x="School Year", y="Percentage of Students", 
       title="Percentage of ACPS Students Enrolled in at least \nOne DE Course by Race: 2019-20 to 2023-24") +
  geom_text(size = 5, hjust=0.5, vjust=-1, color="black") +
  scale_color_manual(values = c("#04994b","#fa8775","#9d02d7","#0c9ed9", "#f8be3d")) +
  theme(legend.title=element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 12, hjust=.5),
        axis.text.x = element_text(color = "black", size = 12, angle = 45, hjust = 1),
        axis.ticks = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot",
        axis.text.y = element_text(size = 12),
        text = element_text(size = 12, family="sans"),
        plot.title = element_text(size = 16, hjust=.65),
        plot.caption = element_text(size = 14))

```

```{r ap_by_econ}
ggplot() +
  geom_line(data=advanced_div %>% dplyr::filter(data_level=="Economic Advantage"),
            aes(x=year,y=perc_ap, group=student_group,color=student_group))+
  theme_minimal()+
  scale_y_continuous(limits=c(0,100),breaks=seq(0,100,10),minor_breaks=seq(0,100,5))+
  labs(x="School Year", y="Percentage of Students", 
       title="Percentage of ACPS Students Enrolled in at least one \nAP Course by Economic Status: 2019-20 to 2023-24")+
  geom_text(size = 5, hjust=0.5, vjust=-1, color="black") +
  scale_color_manual(values = c("#f8be3d","#04994b")) +
  theme(legend.title=element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 12, hjust=.5),
        axis.text.x = element_text(color = "black", size = 12, angle = 45, hjust = 1),
        axis.ticks = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot",
        axis.text.y = element_text(size = 12),
        text = element_text(size = 12, family="sans"),
        plot.title = element_text(size = 16, hjust=.65),
        plot.caption = element_text(size = 14))

```
```{r de_by_econ}
ggplot() +
  geom_line(data=advanced_div %>% dplyr::filter(data_level=="Economic Advantage"),
            aes(x=year,y=perc_de, group=student_group,color=student_group))+
  theme_minimal()+
  scale_y_continuous(limits=c(0,100),breaks=seq(0,100,10),minor_breaks=seq(0,100,5))+
  labs(x="School Year", y="Percentage of Students", 
       title="Percentage of ACPS 10-12th Graders Enrolled in at least one \nDE Course by Economic Status: 2019-20 to 2023-24")+
  geom_text(size = 5, hjust=0.5, vjust=-1, color="black") +
  scale_color_manual(values = c("#f8be3d","#04994b")) +
  theme(legend.title=element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 12, hjust=.5),
        axis.text.x = element_text(color = "black", size = 12, angle = 45, hjust = 1),
        axis.ticks = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot",
        axis.text.y = element_text(size = 12),
        text = element_text(size = 12, family="sans"),
        plot.title = element_text(size = 16, hjust=.65),
        plot.caption = element_text(size = 14))

```