---
title: "Graduation Rates for Equity Audit"
author: "Asha Muralidharan"
date: "2025-03-19"
output: html_document
---
##############################################################
# ACPS STUDENT Success Audit - Graduation Charts       
# Authors: Asha Muralidharan     
# GitHub: asha-ec                              
# Last revised: 2025-03-19
# Summary: A document that creates charts on Graduation Rates
#          for ACPS Audit
##############################################################

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
##############################################################
# Call Libraries
##############################################################

library(readxl)
library(dplyr)
library(tidyverse)
library(ggplot2)

grad <- read_csv("../data/ACPS_graduation_data_2008-24.csv")
```

```{r byschool}
##############################################################
# Graduation Rates by School
##############################################################

ggplot() +
  geom_line(data=grad %>% dplyr::filter(data_level=="All",is.na(school_name)),
            aes(x=cohort_year,y=graduation_rate,color=level)) +
  geom_line(data=grad %>% dplyr::filter(data_level=="All",!is.na(school_name)),
            aes(x=cohort_year,y=graduation_rate,color=school_name)) +
  theme_minimal()+
  scale_x_continuous(limits=c(2011,2024),breaks=seq(2011,2024,1),
                     labels=c("2010-11","2011-12","2012-13","2013-14","2014-15","2015-16",
                              "2016-17","2017-18","2018-19","2019-20","2020-21","2021-22",
                              "2022-23","2023-24"))+
  scale_y_continuous(limits=c(60,100),breaks=seq(60,100,5),minor_breaks=seq(60,100,1))+
  labs(x="Year of Graduation", y="On-Time Graduation Rate")+
  geom_text(size = 5, hjust=0.5, vjust=-1, color="black") + 
  scale_color_manual(name = "School",
                     labels = c("Albemarle High"="Albemarle High School",
                     "Division"="Albemarle County Public Schools",
                     "Monticello High"="Monticello High School",
                     "State"="Virginia", 
                     "Western Albemarle High"="Western Albemarle High School"),
                     values= c("#9d02d7", "#04994b", "#0C9ED9", "#fa8775", "#F8BE3D"),
                     guide = guide_legend(override.aes = list(linewidth = 2),nrow=2))+
  theme(legend.title=element_blank(), 
        legend.position = "top", 
        legend.text = element_text(size = 10, hjust=.5), 
        axis.text.x = element_text(color = "black", size = 10, angle = 45, hjust = 1), 
        axis.ticks = element_blank(),
        plot.title.position= "plot", 
        plot.caption.position = "plot", 
        axis.text.y = element_text(size = 10), 
        text = element_text(size = 12, family="sans"), 
        plot.title = element_text(size = 16, hjust=.65), 
        plot.caption = element_text(size = 14))
  
 ggsave("../plots/grad_school.png",device="png",width=8,height=4,units="in")


```

```{r byrace}
##############################################################
# Graduation Rates by Race
##############################################################

ggplot() +
  geom_line(data=grad %>% dplyr::filter(data_level=="Race",level=="Division",
                                        subgroup!="American Indian or Alaska Native",
                                        subgroup!="Native Hawaiian  or Pacific Islander"),
            aes(x=cohort_year,y=graduation_rate,color=subgroup)) +
  theme_minimal()+
  scale_x_continuous(limits=c(2011,2024),breaks=seq(2011,2024,1),
                     labels=c("2010-11","2011-12","2012-13","2013-14","2014-15","2015-16",
                              "2016-17","2017-18","2018-19","2019-20","2020-21","2021-22",
                              "2022-23","2023-24"))+
  scale_y_continuous(limits=c(60,100),breaks=seq(60,100,5),minor_breaks=seq(60,100,1))+
  labs(x="Year of Graduation", y="On-Time Graduation Rate")+
  scale_color_manual(name = "Race/Ethnicity",
                     labels = c("Asian"="Asian",
                                "Black, not of Hispanic origin"="Black",
                                "Hispanic"="Hispanic",
                                "Non-Hispanic, two or more races"="Multiracial",
                                "White, not of Hispanic origin"="White"),
                     values = c("#04994b","#fa8775","#9d02d7","#0c9ed9", "#f8be3d"),
                     guide = guide_legend(override.aes = list(linewidth = 2)))+
  geom_text(size = 5, hjust=0.5, vjust=-1, color="black") +
  theme(legend.title=element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 12, hjust=.5),
        axis.text.x = element_text(color = "black", size = 12, angle = 45, hjust = 1),
        axis.ticks = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot",
        axis.text.y = element_text(size = 12),
        text = element_text(size = 12, family="sans"),
        plot.title = element_text(size = 16, hjust=.65),
        plot.caption = element_text(size = 14))

 ggsave("../plots/grad_race.png",device="png",width=8,height=4,units="in")


```

```{r bystudentsubgroup}

##############################################################
# Graduation Rates by Student Subgroup
##############################################################
  
ggplot() +
  geom_line(data=grad %>% dplyr::filter(data_level=="All",level=="Division"),
            aes(x=cohort_year,y=graduation_rate,color=subgroup)) +
  geom_line(data=grad %>% dplyr::filter(data_level=="Economic Advantage",level=="Division",
                                        subgroup!="Non-ECD"),
            aes(x=cohort_year,y=graduation_rate,color=subgroup)) +
  geom_line(data=grad %>% dplyr::filter(data_level=="English Learner",level=="Division",
                                        subgroup!="Non-English Learner"),
            aes(x=cohort_year,y=graduation_rate,color=subgroup)) +
  geom_line(data=grad %>% dplyr::filter(data_level=="Disability",level=="Division",
                                        subgroup!="Non-Disabled"),
            aes(x=cohort_year,y=graduation_rate,color=subgroup)) +
  theme_minimal()+
  scale_x_continuous(limits=c(2011,2024),breaks=seq(2011,2024,1),
                     labels=c("2010-11","2011-12","2012-13","2013-14","2014-15","2015-16",
                              "2016-17","2017-18","2018-19","2019-20","2020-21","2021-22",
                              "2022-23","2023-24"))+
  scale_y_continuous(limits=c(60,100),breaks=seq(60,100,5),minor_breaks=seq(60,100,1))+
  labs(x="Year of Graduation", y="On-Time Graduation Rate")+
  geom_text(size = 5, hjust=0.5, vjust=-1, color="black") + 
  scale_color_manual(name = "Membership Group",
                     labels = c("Economically Disadvantaged"="Economically Disadvantaged",
                                "English Learner"="English Learner",
                                "Disabled"="Students with Disabilities",
                                "None"="All Students"),
                     values= c("#9d02d7", "#04994b", "#0c9ed9", "#f8be3d"),
                     guide = guide_legend(override.aes = list(linewidth = 2)))+
  theme(legend.title=element_blank(), 
        legend.position = "top", 
        legend.text = element_text(size = 10, hjust=.5), 
        axis.text.x = element_text(color = "black", size = 12, angle = 45, hjust = 1), 
        axis.ticks = element_blank(),
        plot.title.position= "plot", 
        plot.caption.position = "plot", 
        axis.text.y = element_text(size = 12), 
        text = element_text(size = 12, family="sans"), 
        plot.title = element_text(size = 16, hjust=.65), 
        plot.caption = element_text(size = 14))

 ggsave("../plots/grad_group.png",device="png",width=8,height=4,units="in")

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
